language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm
    - hhvm-nightly

matrix:
    include:
        - php: 5.3
          env: DEPENDENCIES='low'
        - php: 5.6
          env: DEPENDENCIES='dev'
    allow_failures:
        - php: 7.0
        - php: hhvm-nightly
        - env: DEPENDENCIES='dev'
    fast_finish: true

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

# We only install Mongo to ensure the container compiles properly with multiple db-drivers
before_script:
    - echo "extension=mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - composer self-update
    - composer require doctrine/mongodb-odm:"1.0.*@dev" --no-update
    - composer require doctrine/mongodb-odm-bundle:"3.0.*@dev" --no-update

install:
    - export SYMFONY_DEPRECATIONS_HELPER=weak
    - export COMPOSER_ROOT_VERSION=dev-master
    - if [ "$DEPENDENCIES" == "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
    - if [ "$DEPENDENCIES" != "low" ]; then travis_retry composer update; fi;
    - if [ "$DEPENDENCIES" == "low" ]; then travis_retry composer update --prefer-lowest; fi;

script: phpunit --configuration phpunit.xml.dist --verbose --exclude-group ""
